
Epoch: 1
torch.Size([6, 100, 100, 100])
torch.Size([6, 98])
Traceback (most recent call last):
  File "main.py", line 87, in <module>
    train_loss = train_func(model, loader_train, optimizer, scaler)
  File "/homes/n20darja/StageCesureCoeur/predict_tavi/Learning2D/train.py", line 33, in train_func
    logits = model(images)
  File "/opt/campux/virtualenv/deeplearning-u20-rtx-3080-pytorch-1.11/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/homes/n20darja/StageCesureCoeur/predict_tavi/Learning2D/models.py", line 37, in forward
    x = x.view(bs * 98, self.in_chans, 100, 100)
RuntimeError: shape '[588, 3, 100, 100]' is invalid for input of size 6000000
Traceback (most recent call last):
  File "main.py", line 87, in <module>
    train_loss = train_func(model, loader_train, optimizer, scaler)
  File "/homes/n20darja/StageCesureCoeur/predict_tavi/Learning2D/train.py", line 33, in train_func
    logits = model(images)
  File "/opt/campux/virtualenv/deeplearning-u20-rtx-3080-pytorch-1.11/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/homes/n20darja/StageCesureCoeur/predict_tavi/Learning2D/models.py", line 37, in forward
    x = x.view(bs * 98, self.in_chans, 100, 100)
RuntimeError: shape '[588, 3, 100, 100]' is invalid for input of size 6000000