
Epoch: 1
Loss : 0.70073
Traceback (most recent call last):
  File "main.py", line 90, in <module>
    acc, auc, f1 = valid_func(model, loader_valid)
  File "/homes/n20darja/StageCesureCoeur/predict_tavi/Learning2D/train.py", line 62, in valid_func
    logits = torch.argmax(logits, dim = 1)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
Traceback (most recent call last):
  File "main.py", line 90, in <module>
    acc, auc, f1 = valid_func(model, loader_valid)
  File "/homes/n20darja/StageCesureCoeur/predict_tavi/Learning2D/train.py", line 62, in valid_func
    logits = torch.argmax(logits, dim = 1)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)