
Epoch: 1
Loss : 0.70841
Traceback (most recent call last):
  File "main.py", line 90, in <module>
    acc, auc, f1 = valid_func(model, loader_valid)
  File "/homes/n20darja/StageCesureCoeur/predict_tavi/Learning2D/train.py", line 61, in valid_func
    logits = logits.cat(logits)
AttributeError: 'Tensor' object has no attribute 'cat'
Traceback (most recent call last):
  File "main.py", line 90, in <module>
    acc, auc, f1 = valid_func(model, loader_valid)
  File "/homes/n20darja/StageCesureCoeur/predict_tavi/Learning2D/train.py", line 61, in valid_func
    logits = logits.cat(logits)
AttributeError: 'Tensor' object has no attribute 'cat'